# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-run-docker:
    machine: # executor type
      image: ubuntu-2204:current

    steps:
      # Étape 1 : Récupérer le code source
      - checkout

      # Étape 2 : Mettre à jour le système et installer Docker si nécessaire
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      # Étape 3 : Construire l'image Docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app .

      # Étape 4 : Vérifier que l'image a été construite
      - run:
          name: Verify Docker Image
          command: docker images | grep my-app

      # Étape 5 : Exécuter le conteneur Docker
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 --name my-app-container my-app

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-run-docker