version: 2.1

jobs:
  build-and-run-docker:
    # Utilisation de l'exécuteur "machine" avec une image Ubuntu 22.04
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout

      - run:
          name: Construire l'image Docker
          command: |
            sudo docker build -t my-app .

      - run:
          name: Vérifier l'image Docker
          command: |
            sudo docker images | grep my-app

      - run:
          name: Exécuter le conteneur Docker
          command: |
            sudo docker run -d -p 80:8080 --name my-app-container my-app

      - run:
          name: Tester le conteneur Docker
          command: |
            sleep 20  # Attendre que le conteneur soit prêt
            curl -X GET http://127.0.0.1/users || (echo "Le conteneur Docker n'a pas répondu comme prévu" && exit 1)

      - run:
        name: Push application Docker image
        command: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKERHUB_USERNAME/circleci-docker-tp2:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $DOCKERHUB_USERNAME/circleci-docker-tp2:$TAG

      - run:
          name: Nettoyer le conteneur Docker
          command: |
            sudo docker stop my-app-container
            sudo docker rm my-app-container

workflows:
  version: 2
  build-and-run:
    jobs:
      - build-and-run-docker